spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/multi-functional-chat
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.generate-ddl=false
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

spring.mvc.view.prefix=classpath:/templates
spring.mvc.view.suffix=.html
